# Generated by Django 5.2.5 on 2025-08-07 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the project', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
                'unique_together': {('name', 'client')},
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ftp', 'FTP'), ('sftp', 'SFTP')], default='sftp', max_length=4, verbose_name='Source Type')),
                ('host', models.CharField(help_text='Server hostname or IP address', max_length=255, verbose_name='Host')),
                ('port', models.IntegerField(default=22, help_text='Server port (22 for SFTP, 21 for FTP)', verbose_name='Port')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('directory', models.CharField(help_text='Directory path where logs are located', max_length=500, verbose_name='Directory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_source', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Log Source',
                'verbose_name_plural': 'Log Sources',
            },
        ),
        migrations.CreateModel(
            name='FileFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('starts_with', 'Starts With'), ('contains', 'Contains'), ('regex', 'Regex Match')], default='starts_with', max_length=11, verbose_name='Filter Type')),
                ('pattern', models.CharField(help_text='Pattern to match files (filename pattern, regex, etc.)', max_length=255, verbose_name='Pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_filter', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'File Filter',
                'verbose_name_plural': 'File Filters',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(help_text='Cron expression (e.g., "0 */6 * * *" for every 6 hours)', max_length=100, verbose_name='Cron Expression')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
