# Generated by Django 5.2.5 on 2025-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='access_key_id',
            field=models.CharField(blank=True, help_text='AWS Access Key ID', max_length=255, verbose_name='Access Key ID'),
        ),
        migrations.AddField(
            model_name='logsource',
            name='bucket_name',
            field=models.CharField(blank=True, help_text='S3 bucket name', max_length=255, verbose_name='Bucket Name'),
        ),
        migrations.AddField(
            model_name='logsource',
            name='prefix',
            field=models.CharField(blank=True, help_text='S3 object prefix/folder path', max_length=500, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='logsource',
            name='region',
            field=models.CharField(blank=True, help_text='AWS region (e.g., us-east-1)', max_length=50, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='logsource',
            name='secret_access_key',
            field=models.CharField(blank=True, help_text='AWS Secret Access Key', max_length=255, verbose_name='Secret Access Key'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='directory',
            field=models.CharField(blank=True, help_text='Directory path where logs are located', max_length=500, verbose_name='Directory'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='host',
            field=models.CharField(blank=True, help_text='Server hostname or IP address', max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='port',
            field=models.IntegerField(blank=True, default=22, help_text='Server port (22 for SFTP)', null=True, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='source_type',
            field=models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'Amazon S3')], default='sftp', max_length=4, verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='logsource',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username'),
        ),
    ]
